Fix failing test that needs to set environment variables
Error message:
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @58d25a40
        at com.exasol.cloudwatch.configuration.EnvironmentConfigurationReaderTest.testMetrics(EnvironmentConfigurationReaderTest.java:19)