Add TLS fingerprint support (#52)
* #51 Upgrade dependencies

* Upgrade docker containers

* Add certificate fingerprint

This is required for TLS connections

* Increment version to 0.2.0

* Downgrade to localstack 0.12.9

See https://github.com/localstack/localstack/issues/5115

* Fix failing test that needs to set environment variables

Error message:
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @58d25a40
        at com.exasol.cloudwatch.configuration.EnvironmentConfigurationReaderTest.testMetrics(EnvironmentConfigurationReaderTest.java:19)

* Rename tests using containers to ...IT

This ensures that `mvn test` only runs unit tests

* Update documentation & release date

* Add tests without specifying fingerprint

* Refactoring: extract EnvironmentVariableProvider

* Fix integration tests for Java 17

java.time.format.DateTimeParseException: Text '2021-12-15T07:30:27.589Z' could not be parsed at index 20
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954)
	at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494)
	at com.exasol.cloudwatch.LocalstackCloudWatchRaw.readTimestamp(LocalstackCloudWatchRaw.java:54)
	at com.exasol.cloudwatch.LocalstackCloudWatchRaw.readMetrics(LocalstackCloudWatchRaw.java:44)
	at com.exasol.cloudwatch.CloudWatchAdapterIT.testMetricPointIsPut(CloudWatchAdapterIT.java:150)

* Implement review findings by @jakobbraun

Co-authored-by: Jakob Braun <jakob.braun@posteo.de>